### ISSUE TITLE
Monero mining instruction

### ISSUE THREAD

**Issue by jbmustaq** [tevador/RandomX#108]
Hi,

I have gone through your instructions at ("https://forum.zcashcommunity.com/t/an-introdction-to-randomx-and-its-benchmarking-tool/33807/10?u=mistfpga") but there is nothing mentioned on how to mine monero with randomx. Can you be kind enough to please provide a layman instruction of specifically mining monero pool or solo with your miner. I will be thankfull.

**Comment by jbmustaq** [comment]
As per your reply I can see that this can only be used for solo mining. can you please explain how this is integrated to monero for mining.

**Comment by BenjaminWegener** [comment]
1. monero isnt forked before october
2. loki is forked since july 24th, see here https://github.com/xmrig/xmrig/releases

**Comment by jbmustaq** [comment]
Thanks alot for the reply.

**Comment by BenjaminWegener** [comment]
https://github.com/xmrig/xmrig/issues/1044

**Comment by mistfpga** [comment]
If you sign up to the forum I can help you further there.  

You cannot currently mine monero with RandomX. 
Loki and wownero have both implemented RandomX with different parameters.
TXChangeCoin has implemented RandomX on top of Monero with default RandomX parameters.

There are a few other coins that already have RandomX in them.   Assuming nothing changes TXChangeCoin will be as close as it gets to real world monero testing.  I am currently updating the instructions to allow people to try pool and solo mining, on that coin.  - I will post an updated guide to the forum within the next few days, along with ryzen memory timings v frequency.

[Full disclosure - I do testing for TXChangeCoin, mainly because I want to do real world testing of my hardware]

Please close this git hub issue and use my forum link for feedback (I am not associated with RandomX in anyway at all and don't really want to mess up their github)

**Comment by jbmustaq** [comment]
just 1 thing before closing this ticket. what algorithm TXChangeCoin is using.

**Comment by jbmustaq** [comment]
my account on forum is on hold until somebody reviews so can you please just let me know about my above question.

**Comment by mistfpga** [comment]
As I mentioned in my initial reply to you 

"TXChangeCoin has implemented RandomX on top of Monero with default RandomX parameters."

So the RandomX parameters that the benchmarking tool uses are the ones TXChangeCoin uses.

**Comment by mistfpga** [comment]
Just to let you know full instructions will be out today.  Give me 2 - 3 hours and I will update the thread.
