### ISSUE TITLE
2990wx threadripper 

### ISSUE THREAD

**Issue by hvpatel0** [tevador/RandomX#116]
I have tried the benchmark with threadripper 2990wx 32 core 64 thread.
The highest I can get is 4000 with 16 thread 16 init. Larges pages are enabled. When running a Loki randomx inget about max 11500 hs. 
I am.not sure what wrong is with the 32 core. It's not an old CPU so based on the spec I was expecting 16khs minimum. Let me know if there is a setting I need to do to optimize the hashes. I am doing this on windows 10 pro.

**Comment by SChernykh** [comment]
First you need to switch it to "Creator mode" in Ryzen master to enable NUMA, then either run 2 copies of the benchmark, one for each NUMA node, or just run xmrig.

**Comment by kio3i0j9024vkoenio** [comment]
You can test RandomX using XMrig v3.1.0

https://github.com/xmrig/xmrig/releases/tag/v3.1.0

This is how I test on Ubuntu:

RandomX testing

wget https://github.com/xmrig/xmrig/releases/download/v3.1.0/xmrig-3.1.0-xenial-x64.tar.gz
tar xvzf xmrig-3.1.0-xenial-x64.tar.gz

cd xmrig-3.1.0

edit config.json:
   "asm": "bulldozer", - change to this if Opteron's 6200 or 6300 otherwise leave it alone
   "donate-level": 1,
   "algo": "rx/test",
   "pools": "randomx-benchmark.xmrig.com:7777",

./xmrig
