### ISSUE TITLE
Is uop cache realistic?

### ISSUE THREAD

**Issue by kg** [tevador/RandomX#162]
The design doc mentions that the loop size (of 256 insns) is intended to enable x86 chips to run entirely out of the uop cache, reducing their disadvantage compared to simpler instruction sets. I'm not sure how this would actually be feasible.

You note that a given instruction decodes to 1-7 x86 instructions (1.8 on average) - that means the maximum jitted size of a 256-insn loop is 1792 x86 instructions. x86 instructions are also multiple bytes in length often which means the size of it can bloat into the multiple kilobyte range. The instruction count seems likely to exhaust the uop cache even on modern intel chips, for example skylake and coffee lake have this reported size for the L0 uop cache:
```
        1,536 µOPs, 8-way set associative
            32 sets, 6-µOP line size
            statically divided between threads, per core, inclusive with L1I
```
Given that it's statically divided up and set associative, I'm not sure how much of the uop cache would actually get devoted to your loop. I think you would need to exhaustively test this to confirm how much time is spent in decode (vtune can probably tell you this, i think?) and you'd want to also see what it looks like for AMD chips.

I don't necessarily see this as a problem - your performance on a small loop will at least benefit from the icache in more cases because it tends to be bigger, for example in coffee lake:
```
    32 KiB, 8-way set associative
        64 sets, 64 B line size
        shared by the two threads, per core
```
however given that it's shared by multiple threads per core, it's possible OS threads or other mining jobs could push your loop out of icache. The most recent study I can find indicates that the average x86 instruction size for typical programs is 2 bytes per instruction, while the maximum length of a valid x86 instruction is 15 bytes, giving a maximum worst case size of 26880 bytes for a worst case program. Obviously average programs would not be nearly this bad, but it seems difficult to prove how often a random program is going to be unusually large, and it's very hard to prove how big the resulting decoded uops will be.

Anyway I ultimately just wanted to point this out, because it seemed potentially important to utilize the uop cache, and that doesn't feel realistic unless you make the loop size much smaller - so you'd either want to lower the loop size (I can imagine this creates new problems) or just eliminate the uop cache part from the design.

One potential solution would be an inner loop outer loop model, where you generate a random inner loop that is designed to be more likely to fit comfortably into both uop cache and icache, and then generate an outer loop that runs some logic before invoking the inner loop a set number of times. In most cases this would ensure the inner loop runs multiple times without flushing the caches, and then you pay the cost of cache misses on the outer loop. This would probably also reduce the necessary maximum size of a program well below 256 instructions.

**Comment by SChernykh** [comment]
It does run out of uOp cache on Intel because the recent Intel JCC erratum broke it and I had to add mitigations for it. Decoding is not a bottleneck in RandomX, but running out of uOp cache saves ~1W of power on Pentium G5400 according to my tests. Average main loop size is less than 1000 uOps on average.

**Comment by tevador** [comment]
> You note that a given instruction decodes to 1-7 x86 instructions (1.8 on average) - that means the maximum jitted size of a 256-insn loop is 1792 x86 instructions. x86 instructions are also multiple bytes in length often which means the size of it can bloat into the multiple kilobyte range.

That's not how it works. Only the CFROUND instruction can produce 7 x86 instructions. The probability that the program consists of only CFROUND instructions is less than 10<sup>-600</sup>.

An average program will translate into ~460 x86 instructions. Since some instruction decode into multiple uops, the whole program will use around 700 slots in the uOp cache on average (including the static parts of the loop). That's much less than the capacity of Intel (1536) or AMD Zen (2048) uOp caches.

While there is a tiny tiny chance that the program won't fit into the uOp cache, it can be ignored in practice.
