### ISSUE TITLE
Running bench w/o --softAes generates invalid instruction exception while trying to perform aesenc instead of logging to CLI

### ISSUE THREAD

**Issue by YetAnotherRussian** [tevador/RandomX#178]
Benchmark crashes @ Illegal Instruction (attempt to perform aesenc) at vm creation:

randomx_vm *vm = randomx_create_vm(flags, cache, dataset);

right before reaching the desired statement:

if ((flags & RANDOMX_FLAG_HARD_AES)) {
	throw std::runtime_error("Cannot create VM with the selected options. Try using --softAes");

---
CPU: Pentium G620

benchmark.exe --mine --jit --threads %NUMBER_OF_PROCESSORS% --init %NUMBER_OF_PROCESSORS% --nonces 10000

Not a great issue btw (--softAes should be used to fix that)

**Comment by tevador** [comment]
That check is actually meaningless because the randomx library doesn't validate the flags you pass it. If you pass a flag that the CPU doesn't support, it will simply crash. You can use the `randomx_get_flags()` function to get the list of flags that the machine supports (`--auto` option in benchmark).
