### ISSUE TITLE
position-independent code

### ISSUE THREAD

**Issue by hyc** [tevador/RandomX#21]
Modern Linux distros now compile with `-fPIE` enabled by default. Linking fails because of absolute references

````
/usr/bin/ld: obj/JitCompilerX86-static.o: relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIC
````

Adding `-no-pie` to CFLAGS, CCFLAGS, and LDFLAGS gets around this for now. Is that what we actually want now, since PIC is slower?

**Comment by tevador** [comment]
I think the culprit is here: [lines 19-21](https://github.com/tevador/RandomX/blob/master/src/asm/program_prologue_load.inc#L19).

Can you try to change the 3 lines to:
```asm
	movapd xmm13, xmmword ptr minDbl[rip]
	movapd xmm14, xmmword ptr absMask[rip]
	movapd xmm15, xmmword ptr signMask[rip]
```
and see if it's fixed?

However, we cannot use this format because MASM (Visual Studio assembler) doesn't support it and generates position independent code automatically. In GCC, you have to ask for RIP-relative addressing mode using the above syntax.

**Comment by hyc** [comment]
That works. So we need an #ifdef __gcc__ or something around this.

**Comment by tevador** [comment]
MASM doesn't support preprocessor directives, so the only option would be to have separate versions of this file for visual studio and gcc.

BTW the fact that MASM doesn't allow explicit RIP relative addressing is annoying. In some cases you might want to for example load the address of the next instruction:
```asm
lea rax, [rip] ; does not compile in MASM
```
