### ISSUE TITLE
FP register loading

### ISSUE THREAD

**Issue by SChernykh** [tevador/RandomX#27]
> Memory operands are loaded as 8-byte values from the address indicated by src. The 8 byte value is interpreted as two 32-bit signed integers and implicitly converted to floating point format

64-bit FP format has 52 bit precision, so low 20 bits of all FP registers will be 0 right after loading. ASIC can have optimizations for this, especially for read-only FP registers. We need to load 64-bit signed integers and convert them to double precision FP with current rounding mode to fill all bits of FP registers.

**Comment by tevador** [comment]
> low 20 bits of all FP registers will be 0 right after loading

This is true, but all mantissa bits are used again after just 1 operation with the register.

> especially for read-only FP registers

Read-only registers are initialized differently and they have full 52-bit mantissa. This is not explicitly stated in the documentation. Code [here](https://github.com/tevador/RandomX/blob/master/src/VirtualMachine.cpp#L51).

> We need to load 64-bit signed integers and convert them to double precision FP with current rounding mode to fill all bits of FP registers

I tried this before, but it turns out that ARM can only convert integers to float in round-to-nearest mode. See https://github.com/tevador/RandomX/issues/4
Limiting integers to just 53 bits requires additional instructions, which decreases ASIC resistance.

**Comment by SChernykh** [comment]
If read-only registers are full 52-bit then this is not an issue. Documentation is a bit unclear on how loading is actually done.
