### ISSUE TITLE
Audit SoWs

### ISSUE THREAD

**Issue by hyc** [tevador/RandomX#38]
Fyi, SoWs from audit/review teams will be uploaded to https://github.com/hyc/RandomxAudits

**Comment by miki-bgd-011** [comment]
Is funding secured, if not how much is secured ?

**Comment by hyc** [comment]
None has been secured yet. We have to submit a funding proposal to the community. First we have to decide which SoWs to pursue.

**Comment by tarris034** [comment]
Background of this companies must be carefully checked, chosen company should be known on the scene for a long time to avoid scams and ASIC companies standing behind them. Ideally we would have at least two separate companies.

**Comment by MoneroChan** [comment]
Something concerns me about X41's SoW
Section 2.3.3.2 Analysis of Possible Hardware Implementations.

- This section is a double edged sword. 

- We have to consider cost-benefit, because we are also 'paying' them to do the work for ASIC manufacturers like Bitmain/Innosilicon, who can use it to get a head start to build a RandomX ASIC against us.

- Suppose the Audit Does discovers Hardware implementations, will it actually make any difference and alter our decision to implement RandomX ? Do we have an 'agreed threshold' to abort? if we are going ahead with RandomX regardless, then this part of the Audit is not good value for money, as we are doing the work for ASIC manufacturers.

**Comment by hyc** [comment]
This isn't really a question - of course a hardware implementation is possible. We simply want to know a ballpark figure of how effective one might be. ASIC manufacturers will each reach their own design decisions based on their own costs, so it's not like this tells them anything they don't already know.

**Comment by shelby3** [comment]
I will look forward to reading those reports when they’re available.

I did not read the contract proposals carefully but just perusing them it seemed to be mostly cryptographers. Are there any ASIC experts contributing to the reports? I will duplicate this question in that that issues thread. You can answer there.

**Comment by tevador** [comment]
@shelby3 

ASIC experts (Tim Olson, Sonia Chen) have repeatedly stated that an estimate of the efficiency of a RandomX ASIC would require almost a complete physical design (several months of work), which would be out of our (financial and time) budget for audits. Without an actual design, it's just guesswork even for experts.

So the audits focus on the security of the PoW with the exception of X41, which will do some limited hardware efficiency analysis.
