### ISSUE TITLE
AESHash1R is not a secure hash function (and that's fine?)

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#62]
*Issue reported in the context of Kudelski Security's audit*

Collisions and preimages for AESHash1R can be found instantaneously, since the message is input as 16-byte blocks xored once with part of the state. (The attack is straightforward given the descriptions of AESHash1R.)

This cryptographic insecurity is likely understood by the authors, we nonetheless believe that AESHash1R should be a secure hash function, for otherwise one can easily determine Scratchpad values that map to a given hash. May not be exploitable but why take the risk?

Furthermore, in our understanding this part of the PoW is not performance critical, so the BLAKE2b-based hash may be used directly instead.

**Comment by tevador** [comment]
We are aware that AES is reversible.

However, the output of AesHash1R is only an intermediate value that is processed by Blake2b to get the final hash ([Specification](https://github.com/tevador/RandomX/blob/master/doc/specs.md#2-algorithm-description), steps 12-14). So an attack against AesHash1R would have to be preceded by inverting at least 128 bits of Blake2b, which is infeasible.

> Furthermore, in our understanding this part of the PoW is not performance critical

It is performance-critical. AesHash1R already takes around 2.5% of the total runtime (on a CPU that has very fast AES, otherwise it can be up to 5%). Blake2b is at least 3-4 times slower in terms of cycles per byte, which would slow down CPUs even further compared to hardware implementations.

**Comment by veorq** [comment]
Ok so the goal of AESHash1R is to be something like a universal hash. Since the properties and security assumptions aren't defined in the document I'm just guessing and prefer to err on the side of caution.

Wasn't expecting that high a share of the runtime. If what you need is just a universal hash then something like UMAC'NH or Poly1305 would probably be faster.

**Comment by tevador** [comment]
The aim of the "hash" is mainly:

* to detect even a single-bit error in the Scratchpad (causing incorrect final PoW)
* to run as fast as possible, because the Scratchpad is rather large at 2 MiB

So it's more like a checksum.

Cryptographic properties are provided by the final Blake2 hash, which combines the content of the Register File and the Scratchpad checksum.

I did a quick research about Poly1305. Its performance seems to be similar to full 10-round AES encryption, so it's 10x slower than AesHash1R. Couldn't find any code for UMAC's NH. `PCLMULQDQ` instruction has 4x lower throughput than AES, so it would run slower on the CPU.

It will be hard to find anything with performance comparable to AES. It would have to use only SIMD primitives since the 'budget' is 4 CPU cycles per 16 bytes.

**Comment by veorq** [comment]
Ok just checked https://www.agner.org/optimize/instruction_tables.pdf and AESENC indeed has better reciprocal throughput than GMAC's PCLMULQDQ on Skylake-X (and both have a 4-cycle latency). Plus Zen has 2 AES units so you get another speed-up. My bad :)

**Comment by tevador** [comment]
The input of the final Blake2 hash ("final state") looks like this:
```
 +---------------------------------+
 |        group R registers        |
 +---------------------------------+
 |        group F registers        |
 +---------------------------------+
 |        group E registers        |
 +---------------------------------+
 |      AesHash1R(Scratchpad)      |
 +---------------------------------+
```
Each of the rows is 64 bytes for a total of 256 bytes.

While it's quite simple to invert the Scratchpad hash (the last 64 bytes), this cannot be used to skip any steps in the PoW algorithm because

* the final register values (input bytes 0-191) are not 'invertible'
* Scratchpad content is not 'invertible'

Even if there were zero Scratchpad writes during VM executon (i.e. the Scratchpad would stay the same as generated by AesGenerator1R in [step 4](https://github.com/tevador/RandomX/blob/master/doc/specs.md#2-algorithm-description)), 'inverting' the Scratchpad into a block template would require finding a preimage of the initial Blake2 hash ([step 2](https://github.com/tevador/RandomX/blob/master/doc/specs.md#2-algorithm-description)).

So, I think it's possible to prove that even a very reduced version of RandomX with steps 5-11 replaced with

* Copy seed `S` into bytes 0-63 of "final state".

is not invertible and no steps can be skipped (just no actual scratchpad memory is required). While such algorithm could be run "backwards" by selecting a Scratchpad hash and calculating the seed `S` by inverting both AesHash1R and AesGenerator1R, the seed itself cannot be inverted into a block template, so this strategy is useless.
