### ISSUE TITLE
Proposal: Coming full circle

### ISSUE THREAD

**Issue by hyc** [tevador/RandomX#7]
My primary concern with randomX and its predecessor CNVM is that the machine specification itself is too simple, and can be implemented in a very minimally equipped CPU. I also still believe that forcing execution of a language processor (i.e., a compiler or interpreter) is a more extensive "CPU-like" task and we should still be leveraging that.

Our main problem with randomJS is that if you can randomly generate a syntactically correct program source code, you can just take the generated AST and execute it directly, instead of bothering to execute the JS.

So, instead, what if we combine these two approaches - we specify a language and a reference compiler implementation that compiles the given language into bytecode. So a valid implementation must generate identical bytecode for a given source text. And then, we feed the bytecode into randomX - which means the generated AST has nothing to do with the resulting execution, so it can't be used as a shortcut. I.e., the bytecode and the randomX instruction set are completely independent entities. This is just a long-winded way of using a compiler to generate the random bytes that randomX will execute.

**Comment by tevador** [comment]
> One more concern: generated bytecode is usually low entropy, maybe add some LZ compression + AES encryption on top of it to get high entropy random data?

Exactly, bytecode/machine code is usually far from random data.

Other issues:
* Verification time will be higher than simply generating a random program.
* More complex PoW.
* RandomX is already pretty close to an ideal CPU workload (IMO).

**Comment by hyc** [comment]
A compressor pass may not be a bad idea, but machine code rarely compresses as well as even 2:1. It's always been far more difficult to compress than e.g. human readable text.

Slower verification time - ok, maybe that's a problem. Maybe it's not worth investigating at this point in time. I've still got reservations about whether randomX is complex enough, but it's probably too early to say.

**Comment by SChernykh** [comment]
What I like about RandomX is that it's fairly simple - reference implementation could probably fit in 1000 lines of code. Adding a compiler before it is a whole bunch of complexity.

**Comment by tevador** [comment]
> A compressor pass may not be a bad idea, but machine code rarely compresses as well as even 2:1. It's always been far more difficult to compress than e.g. human readable text.

Executable code typically compresses to around 30-40% so there are only ~3 random bits per byte. RandomX needs a completely uniform random input. For example, a single non-uniform bit can cause the program to never read from the 4 GB dataset or to not have any branches.

Anyways, it could be solved by compression or encryption, so it's not a fundamental issue.

> I've still got reservations about whether randomX is complex enough, but it's probably too early to say.

Given the limitations of portability, I think RandomX utilizes CPU hardware fairly well:

* All primitive ALU operations
* Most floating point operations defined by IEEE-754
* Branches/recursion
* Stack
* L1, L2 cache
* Large external memory with both sequential and random access

Do you think a compiler can do significantly better?

Since the PoW will have to be audited, I prefer the implementation to be as simple as possible.
