### ISSUE TITLE
Type mismatch causing potential integer overflow in datasetInit()

### ISSUE THREAD

**Issue by veorq** [tevador/RandomX#70]
In randomx.cpp:
```
	void randomx_init_dataset(randomx_dataset *dataset, randomx_cache *cache, unsigned long startItem, unsigned long itemCount) {
		cache->datasetInit(cache, dataset->memory + startItem * randomx::CacheLineSize, startItem, startItem + itemCount);
	}
```
here `datasetInit()` will actually call `initDataset()` defined in dataset.cpp:

```
	void initDataset(randomx_cache* cache, uint8_t* dataset, uint32_t startItem, uint32_t endItem) {
		for (uint32_t itemNumber = startItem; itemNumber < endItem; ++itemNumber, dataset += CacheLineSize)
			initDatasetItem(cache, dataset, itemNumber);
	}
```

The types of `startItem` and `endItem` are 32-bit (`uint32_t`) in the former function, whereas they were initially 64-bit (`unsigned long` ) on 64-bit platforms.
In the unlikely case that `randomx_init_dataset()` be called with greater than 2^32 values, the initialization would not behave as expected.

Could be fixed by ensuring that these numbers have types of the same lengths.

**Comment by tevador** [comment]
I don't think it's an issue in practice. 

The Dataset size is `RANDOMX_DATASET_BASE_SIZE + RANDOMX_DATASET_EXTRA_SIZE = 2181038016`, so there are only 34078719 items (each item is 64 bytes).  If `randomx_init_dataset` is called with an item number `34078719` or larger, it will most likely result in a crash because the function will attempt to write past the end of the memory buffer. It's the responsibility of the API user to make sure all item numbers are in the range `0` to `34078718`.

**Comment by veorq** [comment]
Agree, doesn't seem exploitable by attackers as they're not supposed to control these inputs.
It may still be good validate inputs and prevent crashes on invalid values.

**Comment by tevador** [comment]
Added `asserts` in #88 to prevent passing invalid values to the function.

#87 limits the Dataset size to a maximum of 16 GiB, so an overflow can never happen without failing an assert.
